spring:
  application:
    name: capstoneProject

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: Cloud@123$

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  ai:
    openai:
      api-key: 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
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.6


server:
  port: 8090

jwt:
  secret: mySecretKeyForCapstoneProjectThatIsAtLeast32CharactersLong
  expiration: 86400000



